/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VxAqeNMr15Z
 */
import { SideBar } from "@/components/base-chat/side-bar"
import { Chat } from "./chat"

export function BaseChatLayout() {
  return (
    <div className="flex h-screen bg-gray-100 dark:bg-gray-900">
      <SideBar />
      <main className="flex flex-col flex-1">
        <div className="flex flex-col flex-1 overflow-y-auto p-6 space-y-4">
          <Chat />
        </div>
      </main>
    </div>
  )
}
