/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VxAqeNMr15Z
 */
import { SideBar } from "@/components/base-chat/side-bar"
import { ChatMain } from "@/components/base-chat/chat-main"
import { InputBox } from "./base-chat/input-box"

export function BaseChatLayout() {
  return (
    <div className="flex h-screen bg-gray-100 dark:bg-gray-900">
      <SideBar />
      <main className="flex flex-col flex-1">
        <ChatMain />
        <InputBox />
      </main>
    </div>
  )
}
